package com.example.smart_campus_operations.entity;

public enum NotificationType {
    BOOKING_APPROVED,
    BOOKING_REJECTED,
    BOOKING_CANCELLED,
    TICKET_STATUS_CHANGED,
    TICKET_CREATED,
    NEW_COMMENT,
    TICKET_ASSIGNED,
    PROFILE_UPDATED,
    FACILITY_ADDED,
    FACILITY_DELETED,
    CUSTOM_NOTIFICATION
}
