spring.application.name=smart-campus-operations

spring.datasource.url=jdbc:mysql://localhost:3306/campus?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=@Banula123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect